name: Bug Report
description: Report a bug in LuiseInstallerX
body:
  - type: markdown
    attributes:
      value: |
        # Before posting an issue
        
        Your issue may already be reported!
        Please search on the [issue tracker](https://github.com/xztimee/LuiseInstallerX/issues) before creating one.
        
        **Note:** LuiseInstallerX is a fork of TrollInstallerX. For issues with the original TrollInstallerX, please visit [alfiecg24/TrollInstallerX](https://github.com/alfiecg24/TrollInstallerX/issues).

  - type: checkboxes
    id: no-duplicates
    attributes:
      label: No Duplicate Issues
      options:
        - label: I've searched the issue tracker and this issue hasn't been reported yet
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Open LuiseInstallerX
        2. Tap 'Install'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: TrollStore should install successfully
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: App crashes or shows error
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        # Device Information

  - type: input
    id: device
    attributes:
      label: Device Model
      description: e.g., iPhone 12 Pro, iPad Air 4
      placeholder: iPhone 12 Pro
    validations:
      required: true

  - type: input
    id: ios-version
    attributes:
      label: iOS Version
      description: e.g., 16.5.1, 15.7.2
      placeholder: 16.5.1
    validations:
      required: true

  - type: input
    id: app-version
    attributes:
      label: LuiseInstallerX Version
      description: Check in app or from release page
      placeholder: v1.0.0
    validations:
      required: true

  - type: dropdown
    id: exploit
    attributes:
      label: Exploit Method
      description: Which exploit method were you using?
      options:
        - Direct Installation (MacDirtyCow/dmaFail)
        - Indirect Installation (kfd)
        - Auto (let app choose)
        - Don't know
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: If available, paste any error messages or logs from the app
      placeholder: Paste logs here...
      render: text

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: Add any other context about the problem here
